"""added genre model

Revision ID: 46726615eec7
Revises: 1a102ccd2e19
Create Date: 2025-11-11 12:11:16.195709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46726615eec7'
down_revision = '1a102ccd2e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###
